{% set name = "aiobotocore" %}
{% set version = "0.10.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "70ace7a7894e17dc19b21a23b39f735557b13eadb85bbcf8d2b3440b8ddf0add" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - botocore >=1.12.189,<1.12.190
    - aiohttp >=3.3.1
    - async_generator >=1.10
    - wrapt >=1.10.10

test:
  imports:
    - aiobotocore

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache 2
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  doc_url: http://aiobotocore.readthedocs.io
  dev_url: https://github.com/aio-libs/aiobotocore

extra:
  recipe-maintainers:
    - nehaljwani
