{% set name = "aiobotocore" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 506591374cc0aee1bdf0ebe290560424a24af176dfe2ea7057fe1df97c4f0467

build:
  skip: true  #[py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - aiohttp >=3.7.4.post0,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.31.16,<1.31.65
    - python
    - wrapt >=1.10.10,<2.0.0
  run_constrained:
    - boto3 >=1.28.16,<1.28.65

test:
  imports:
    - aiobotocore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  dev_url: https://github.com/aio-libs/aiobotocore
  doc_url: https://aiobotocore.readthedocs.io
  

extra:
  recipe-maintainers:
    - nehaljwani
