{% set name = "aiobotocore" %}
{% set version = "2.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aio-libs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a4a6acc4b766691a9d1d8ba4a262828c53609d34f37691ceefb95e482aaf703c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=68.2.0
    - wheel
  run:
    - python
    - aiohttp >=3.9.2,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.39.7,<1.39.9
    - python-dateutil >=2.1,<3.0.0
    - jmespath >=0.7.1,<2.0.0
    - multidict >=6.0.0,<7.0.0
    - wrapt >=1.10.10,<2.0.0
  run_constrained:
    - awscli >=1.41.7,<1.41.9
    - boto3 >=1.39.7,<1.39.9
    - httpx >=0.25.1,<0.29

test:
  imports:
    - aiobotocore
    - aiobotocore._endpoint_helpers
    - aiobotocore._helpers
    - aiobotocore.awsrequest
    - aiobotocore.config
    - aiobotocore.credentials
    - aiobotocore.endpoint
    - aiobotocore.eventstream
    - aiobotocore.httpchecksum
    - aiobotocore.httpsession
    - aiobotocore.httpxsession
    - aiobotocore.parsers
    - aiobotocore.response
    - aiobotocore.retries
    - aiobotocore.retries.adaptive
    - aiobotocore.session
    - aiobotocore.signers
    - aiobotocore.stub
    - aiobotocore.tokens
    - aiobotocore.utils
    - aiobotocore.waiter
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Missing specific 'boto3' dependency version required by 'moto'. Consider re-running tests after the next version bump.
    # - pytest -v tests
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  dev_url: https://github.com/aio-libs/aiobotocore
  doc_url: https://aiobotocore.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani