{% set name = "aiobotocore" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aio-libs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d3c77c17f006a1748b9a63ea8a0aef454cc9385fc37b7134ccab949f899ac652

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.0
  run:
    - python
    - aiohttp >=3.12.0,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.41.0,<1.42.20
    - python-dateutil >=2.1,<3.0.0
    - jmespath >=0.7.1,<2.0.0
    - multidict >=6.0.0,<7.0.0
    - typing-extensions >=4.14.0,<5.0.0  # [py<311]
    - wrapt >=1.10.10,<2.0.0
  run_constrained:
    - httpx >=0.25.1,<0.29

# Need to rebuild s3transfer 0.2.0 to run tests, won`t do.
test:
  imports:
    - aiobotocore
    - aiobotocore._endpoint_helpers
    - aiobotocore._helpers
    - aiobotocore.awsrequest
    - aiobotocore.config
    - aiobotocore.credentials
    - aiobotocore.endpoint
    - aiobotocore.eventstream
    - aiobotocore.httpchecksum
    - aiobotocore.httpsession
    - aiobotocore.httpxsession
    - aiobotocore.parsers
    - aiobotocore.response
    - aiobotocore.retries
    - aiobotocore.retries.adaptive
    - aiobotocore.session
    - aiobotocore.signers
    - aiobotocore.stub
    - aiobotocore.tokens
    - aiobotocore.utils
    - aiobotocore.waiter
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip


about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  dev_url: https://github.com/aio-libs/aiobotocore
  doc_url: https://aiobotocore.aio-libs.org

extra:
  recipe-maintainers:
    - nehaljwani