{% set name = "aiobotocore" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0603b74a582dffa7511ce7548d07dc9b10ec87bc5fb657eb0b34f9bd490958bf

build:
  skip: true  #[py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - aiohttp >=3.3.1
    - aioitertools >=0.5.1
    - botocore >=1.27.59,<1.27.60
    - python
    - wrapt >=1.10.10

test:
  imports:
    - aiobotocore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  dev_url: https://github.com/aio-libs/aiobotocore
  doc_url: https://aiobotocore.readthedocs.io
  

extra:
  recipe-maintainers:
    - nehaljwani
