{% set name = "aiobotocore" %}
{% set version = "0.5.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5173e62dfa0ef73636bd4ff20539d420cab60e0348d8e6c7f67882c9b2fa3b1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py<34]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - botocore >=1.7.28,<=1.7.40
    - aiohttp >=2.3.0,<3.0.0
    - multidict >=2.1.4
    - wrapt >=1.10.10
    - packaging >=16.8

test:
  imports:
    - aiobotocore

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache 2
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  doc_url: http://aiobotocore.readthedocs.io
  dev_url: https://github.com/aio-libs/aiobotocore

extra:
  recipe-maintainers:
    - nehaljwani
