{% set name = "aiobotocore" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aio-libs/aiobotocore/archive/{{ version }}.tar.gz
  sha256: b93579fac2dafa523933bcd1706f9b611fdde4f3020b16f33ca3416be13b6900

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  #[py<38]

requirements:
  host:
    - python
    - pip
    - setuptools >=68.2.0
    - wheel
  run:
    - python
    - aiohttp >=3.9.2,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.36.0,<1.36.4
    - python-dateutil >=2.1,<3.0.0
    - jmespath >=0.7.1,<2.0.0
    - multidict >=6.0.0,<7.0.0
    - urllib3 >=1.25.4,<1.27  # [py<310]
    - urllib3 >=1.25.4,!=2.2.0,<3  # [py>=310]
    - wrapt >=1.10.10,<2.0.0
  run_constrained:
    # https://github.com/aio-libs/aiobotocore/blob/2.19.0/pyproject.toml#L44
    - awscli >=1.37.0,<1.37.4
    - boto3 >=1.36.0,<1.36.4

test:
  source_files:
    - tests
  imports:
    - aiobotocore
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  dev_url: https://github.com/aio-libs/aiobotocore
  doc_url: https://aiobotocore.readthedocs.io

extra:
  recipe-maintainers:
    - nehaljwani
