travis:
  secure:
    BINSTAR_TOKEN: h/RCncazv+51Wdo2iZLG0Kkth9SNLWPo+ggjJHEncK9QpiWLrD8rDTREZFpCsXarFvyFiU+nZgiWGYgUmqAw2TroiZ5uUxJ6GrKKIEKEIVKiMGDdH4/rxYkFgvUDlIV2mORlNA3Yncol0h/YKJA3d1ILng7fCPYauFdvV2j7zoDFhonuIKWnnhow4sy+0xr0vcBVa7aljNwhxbO6cuBj+9GB8t+WL7d5ADWeweJ5Bvw7+nGsz8CpqUwreC2ARO7M4wourq0A2DpEaoRrNf7JysyBbx/a9spNDB4HWiKpSOKEKf8LNKGuOjApphl8b49nLs/8xcZs4SUHhUH1a6hx0OHWzbKqUkg1uiU95iNFwoEpg9tG3Yanaz7iwi8N1p19aq+anCG2Upcctazy9SGwP7iUoNxlAQ5td4XNNWNewiTSIpyX9Dhg5JUZexAqvz3Z0TpmSHwwuH4K3pb57oGidHfZabCYnOwjJHgmeEBARWeU1vBDIE6BLT99xpu3WAO5rCzyI0jCBqmprt4PfK3hSrS8pSDZ8Rta3FzJi1hUxVDpFLwBLmun5e8t4/0krY/Xt1giCQi5xAnZuDDPpHkd2cCngyudvPcKAvMe1pw2HtLGGrIQXKy+353b0d/FSTI/JJh8ADUiXv9bl7arHxkzSwp/gabvL+av6MITOzfQP5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
