travis:
  secure:
    BINSTAR_TOKEN: uYiS+ediFxiatvDytmqkFKrtMI/iXKXminOGGZ4sNWbI6niZIjJlRHTpieN5L6E7UNHdEbeMwflPIFmDWoLkZ0K1pEQv8fFnjMl7k9cKJw8tmba4eAQnf4yWzMWWZ7VCsNxS3MCgtyqwaECvkkEehfWi+NZKBmHptXBOADPNIV1ddJEnaWijbC5Q8RmyKlWaIIwfh0r6Oq7rfLxEfwoGYSJaNlo1yJ42p3cdx5ghsz2aNyKJUvYlNXbeIawZ8jGCBRfEJrLrWr+HP9JtXGxbAuBYC3zJUrQsn9KaJgKjNZcGx2VwOSq5yx8yeI90YmE3TGZ+Uki8kX4HpH4YFfHu3XGy3F4t6firy2xipT5rXEa7u5nfmp+clsw4Lo2fmkVo852YdaS07GdN0zYUobfu/rR96RZWDX1iKOZyzLbL3vBXNMPrRroDBa6XFjhTqJVOkSxMu9rSXqQeviZAfNDXWYTjhqB4f8iysk1jGUUige9NrZ2Id0MHv2Q6UeWucnLcSodWF7N5I8GdKxKvOyuHAadcznk37uf8qMvZVEFWp2iApkJpcvgbQrRbvFX3Ok6o35cuVQMjewS3FiEzpQncTjki6RwezYB9cjkHAY1pI4hsA3z0+qzQu9IEudlOyfMwki7fQ4Z+CDjY+E/DTPl11r+eKfPcUirTYRX9HicBI/0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
