travis:
  secure:
    BINSTAR_TOKEN: A5AaJUM7IYLKDXmEPzCts0NINDQA8EwXshJzv/Bqo2jQ9UjtitZDLS8jCcV2iUgu8Uput7XIlNaK8Z3+wg5fVINUVek4Mj+FxNhNz0TZrcrjT4qYFMZDy3q3H9XXk18xV4rIBHW8pGISeHTgUBJFRPMvXtKWKJ2Pqn10wrqZyL1rhMEuZopsZH5j0aFDMhoocfAD7BewdqutP2IWs6wSiCbROKtJ5+BNrY+AMcAJzOGaFIJ1WIvJlwJLnFDRMBUECW0BajwSfarre6aUJv/G7z/ajWpevO+kccu6Q0GCwV/TY7aKAE4iP+RctIPBuV0P9KfeqiQzen/JEwVCTgCXrbpQwOHHLna4McbgyyrlL9hWS8Y4hIeSJRBCu6RnqRDSRdvvlQN3qUseu9/3OFFh9mSRUMQrLGMMr21OoPiWAicbCvn8FUHalEJSZls0kUS7GEYzw4h16wgUKQb8A46rKxcvztI6dG9c81onV0Rs1lkDqvIzfiTUZ3x4cC3oz906LHS0CuqlqYHK9JIlxEonD5/cY/MkNLMXJIA/oO8rZog/kBRRC/mi17mzdCMKW9mEv2u7miTMNZ8euFKId24w/pC2Th+IFofeNXDrisFUh5Tk4f6LLyywminA3KMMXdeJLCxZNB6ow42S10wX9cHoNMNIaAcHbmiUAT3lEM0T+9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
